const http=require("http"),fs=require("fs"),path=require("path");const {URL}=require("url");
const PORT=Number(process.env.PORT||8787),PUBLIC=path.join(__dirname,"public"),clients=new Set(),tokens=new Map();
const send=(r,c,d)=>{r.writeHead(c,{"Content-Type":"application/json","Cache-Control":"no-store"});r.end(JSON.stringify(d))};
const broadcast=(e,d)=>{const x=`event: ${e}\ndata: ${JSON.stringify(d)}\n\n`;for(const r of clients){try{r.write(x)}catch{}}};
async function getJSON(u){const r=await fetch(u,{headers:{accept:"application/json"}});if(!r.ok)throw Error(r.status);return r.json()}
function signal(p,r){const pc=+p?.priceChange?.m5||0,h=+p?.priceChange?.h1||0,b=+p?.txns?.h1?.buys||0,s=+p?.txns?.h1?.sells||0,l=+p?.liquidity?.usd||0,f=b+s?b/(b+s):.5;let x=50+pc*1.15+h*.25+(f-.5)*45+Math.min(12,Math.log10(Math.max(1,l))*2);if(r?.scoreNormalized!=null)x-=Math.min(30,r.scoreNormalized*.3);x=Math.max(0,Math.min(100,x));return{score:Math.round(x),label:x>=72?"WATCH":x>=55?"MOMENTUM":"CAUTION"}}
async function enrich(t){try{const a=await getJSON(`https://api.dexscreener.com/token-pairs/v1/solana/${encodeURIComponent(t.mint)}`),p=Array.isArray(a)?a.filter(x=>x?.chainId==="solana").sort((a,b)=>(+b?.liquidity?.usd||0)-(+a?.liquidity?.usd||0))[0]:null;let r=null;try{const z=await getJSON(`https://api.rugcheck.xyz/v1/tokens/${encodeURIComponent(t.mint)}/report`),raw=+z?.score;r={scoreRaw:Number.isFinite(raw)?raw:null,scoreNormalized:Number.isFinite(raw)?Math.max(0,Math.min(100,raw>100?raw/200:raw)):null,rugged:!!z?.rugged}}catch{}return{...t,pair:p,rug:r,signal:signal(p,r),updatedAt:Date.now()}}catch{return{...t,pair:null,rug:null,signal:{score:0,label:"NEW"},updatedAt:Date.now()}}}
async function add(e){if(!e?.mint)return;const t={mint:String(e.mint),name:String(e.name||"Unknown"),symbol:String(e.symbol||"TOKEN"),creator:String(e.traderPublicKey||""),uri:String(e.uri||""),createdAt:Number(e.created_timestamp||Date.now())};if(tokens.has(t.mint))return;tokens.set(t.mint,t);while(tokens.size>80)tokens.delete(tokens.keys().next().value);broadcast("token",t);const z=await enrich(t);tokens.set(t.mint,z);broadcast("update",z)}
function connect(){try{const w=new WebSocket("wss://pumpportal.fun/api/data");w.onopen=()=>{w.send(JSON.stringify({method:"subscribeNewToken"}));w.send(JSON.stringify({method:"subscribeMigration"}));broadcast("status",{ok:true})};w.onmessage=e=>{try{add(JSON.parse(String(e.data)))}catch{}};w.onclose=()=>setTimeout(connect,3000);w.onerror=()=>broadcast("status",{ok:false})}catch{setTimeout(connect,3000)}}
setInterval(async()=>{for(const t of [...tokens.values()].slice(0,25)){const z=await enrich(t);tokens.set(t.mint,z);broadcast("update",z)}},12000);
http.createServer((req,res)=>{const u=new URL(req.url,`http://${req.headers.host||"localhost"}`);if(u.pathname==="/api/tokens")return send(res,200,[...tokens.values()]);if(u.pathname==="/events"){res.writeHead(200,{"Content-Type":"text/event-stream","Cache-Control":"no-cache","Connection":"keep-alive"});res.write(`event: snapshot\ndata: ${JSON.stringify([...tokens.values()])}\n\n`);clients.add(res);req.on("close",()=>clients.delete(res));return}const f=path.join(PUBLIC,u.pathname==="/"?"index.html":u.pathname);if(!f.startsWith(PUBLIC))return send(res,403,{error:"forbidden"});fs.readFile(f,(e,d)=>{if(e)return send(res,404,{error:"not found"});res.writeHead(200,{"Content-Type":path.extname(f)===".html"?"text/html":"text/plain"});res.end(d)})}).listen(PORT,()=>{console.log("PumpScope on "+PORT);connect()});